<a href="https://colab.research.google.com/github/hseyeon1006/ESAA_YB/blob/main/bbb%20HW1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## HW1

### problem 1. Range and For loop

    (a) For loop와 range를 사용하여 0부터 100까지 정수만 출력하는 코드를 작성하시오.

In [2]:
for i in range(0,101):
  print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100


    (b) For loop와 range를 사용하여 0부터 100까지 정수 중 7로 나누어 떨어지는 정수만 출력하는 코드를 작성하시오

In [10]:
a=[]
for i in range(0,101):
  if i%7==0:
    a.append(i)
print(a)

[0, 7, 14, 21, 28, 35, 42, 49, 56, 63, 70, 77, 84, 91, 98]


    (c) For loop와 range를 사용하여 1부터 100까지 정수 중 5로 나누어 떨어지지만 3으로 나누어 떨어지지 않는 정수를 출력하는 코드를 작성하시오

In [7]:
a=[]
for i in range(1,101):
  if (i%5==0) & (i%3!=0):
    a.append(i)
print(a)

[5, 10, 20, 25, 35, 40, 50, 55, 65, 70, 80, 85, 95, 100]


    (d) 정수를 입력받은 후 1부터 입력받은 정수까지 짝수들의 합을 구하는 코드를 작성하시오.

      - 입력값으로 27을 넣은 후 결과값을 첨부할 것.
      - For문과 if문을 이용할 것

In [11]:
a = int(input())
j=0
for i in range(1,a+1):
  if i%2==0:
    j+=i
print(j)

27
182


### problem 2. While loops

    (a) While loops를 이용하여 0부터 100까지 6으로 나누어 떨어지는 정수를 출력하는 코드를 작성하시오.

In [15]:
i=0
a=[]
while i<=100:
  if i%6==0:
    a.append(i)
  i+=1 
print(a)

[0, 6, 12, 18, 24, 30, 36, 42, 48, 54, 60, 66, 72, 78, 84, 90, 96]


    (b) While loops를 이용하여 5,7, 11로 나누어 떨어지는 정수를 20개 출력하는 코드를 작성하시오.

In [16]:
a=[]
i=0
while len(a)<=20:
  if (i%5==0) & (i%7==0) & (i%11==0):
    a.append(i)
  i+=1
print(a)

[0, 385, 770, 1155, 1540, 1925, 2310, 2695, 3080, 3465, 3850, 4235, 4620, 5005, 5390, 5775, 6160, 6545, 6930, 7315, 7700]


### problem 3. Fibonacci sequence

   (a) Fibonacci sequence는 a0 = 0, a1 = 1 으로 시작하며 다음과 같은 식으로 정의된다.
an+2 = an+an+1
Fibonacci sequence을 함수로 정의한 후 그 코드를 작성하시오. 또한, 정의한 함수를 이용
하여 a35를 구하시오.

In [17]:
def fib(x):
  if x==0:
    return 0
  elif x==1:
    return 1
  else:
    return fib(x-1)+fib(x-2)

print(fib(35))

9227465


### problem 4

In [78]:
import numpy as np
import random

    (a) 1부터 20까지 10개의 정수(난수)를 생성하는 코드를 작성하시오. (random seed : 1886)
        (Hint : array를 list로 바꾸는 code는 list_name.tolist() 이다.)

In [79]:
np.random.seed(1886)
a=np.random.randint(1,20,10)
print(a)

[ 7 14  2 10  5  5  4 11  4  7]


    (b) (a)의 list(혹은 array)에서 첫번째부터 다섯번째까지의 원소를 출력하는 코드를 작성하시오.

In [28]:
a[0:5]

array([ 7, 14,  2, 10,  5])

    (c) 다음 결과를 출력하도록 하는 Indexing code를 작성하는 코드를 작성하시오.

In [29]:
a[1:6:2]

array([14, 10,  5])

    (d) 다음 결과를 출력하도록 하는 Indexing code를 작성하는 코드를 작성하시오.

In [30]:
a[5::-1]

array([ 5,  5, 10,  2, 14,  7])

    (e) 다음 결과를 출력하도록 하는 Indexing code를 작성하는 코드를 작성하시오.

In [31]:
a[:7:-1]

array([7, 4])

### problem 5

    (a) 1 부터 20 사이의 정수에서 난수를 생성하여 데이터 프레임을 만드는 코드를 작성하시오. (random seed : 123)

        - size = (5,6) 으로 지정
        - colname = [‘col1’, ‘col2’, …, ‘col6’] 으로 지정
        - index = [‘row1’, ‘row2’, …, ‘row5’] 으로 지정

In [33]:
import numpy as np
import pandas as pd
import random

In [37]:
np.random.seed(123)
df = pd.DataFrame(np.random.randint(1,20,(5,6)),
                  columns = ['col1','col2','col3','col4','col5','col6'],
                  index = ['row1','row2','row3','row4','row5'])
print(df)

      col1  col2  col3  col4  col5  col6
row1    14     3     3     7    18    11
row2     2     1    18    16    10     1
row3    15     1    16    15     5     1
row4    17     5    18     4     3     8
row5     3    16    17     8    10     4


    (b) (a)에서 만든 데이터 프레임에서 마지막 3줄을 출력하는 코드를 작성하시오.

In [39]:
df[-3:]

col1  col2  col3  col4  col5  col6
row3    15     1    16    15     5     1
row4    17     5    18     4     3     8
row5     3    16    17     8    10     4

    (c) row2와 row3만을 출력하는 코드를 작성하시오.

In [40]:
df[1:3]

col1  col2  col3  col4  col5  col6
row2     2     1    18    16    10     1
row3    15     1    16    15     5     1

    (d) col4와 col5를 출력하는 코드를 작성하시오.

In [41]:
df[['col4','col5']]

col4  col5
row1     7    18
row2    16    10
row3    15     5
row4     4     3
row5     8    10

    (e) row3 그리고 col6에 해당하는 데이터를 추출하는 코드를 작성하시오.

In [42]:
df.loc['row3','col6']

1

    (f) col1의 데이터가 5보다 큰 데이터 중에서 col2와 col3만을 추출하는 코드를 작성하시오.

In [43]:
df.query('col1>5')[['col2','col3']]

col2  col3
row1     3     3
row3     1    16
row4     5    18

### problem 6

     (a) 다음 조건을 만족하는 함수를 만드시오. 함수 이름은 my_max(x,y)로 정의하며, x와 y가 input으로 들어간 후 둘 중 큰 수를 return한다. Python의 내장 함수 max()를 사용하지 않으며, if문을 이용하여 함수를 만든 후 그 코드를 작성하고, 임의의 두 숫자를 넣어 그 결과를 작성하시오.

In [44]:
import numpy as np
import pandas as pd

In [45]:
x=int(input())
y=int(input())

def my_max(x,y):
  if x>y:
    return x
  elif x<y:
    return y
  else:
    print("x와 y 값이 다르도록 다시 수를 정해주세요")

my_max(x,y)

15
17


17

    (b) 1부터 100까지 0.1씩 증가하여 숫자를 생성한 후 함수 y = 3x^2 -x+2 의 plot을 그리시오.

### problem 7 

    (a) 입력된 list에서 홀수인 원소만 빼내는 함수를 만드시오.

        - 함수 이름은 ‘myodd’로 지정할 것.
        - for문과 if문을 이용할 것

In [61]:
def myodd(a):
  a=list(map(int, input().split()))
  b=[]
  for i in a:
    if i%2==1:
      b.append(i)
  return b

myodd(a)

1 2 3 4 5


[1, 3, 5]

    (b) (a)에서 만든 함수를 mymodule이라는 이름의 .py로 저장하시오.

In [70]:
from google.colab import drive
drive.mount('/content/mydrive')

Drive already mounted at /content/mydrive; to attempt to forcibly remount, call drive.mount("/content/mydrive", force_remount=True).


In [75]:
from google.colab import files
src = list(files.upload().values())[0]
open('mymodule.ipynb','wb').write(src)

Saving mymodule.ipynb to mymodule (2).ipynb


641

    (c) 1부터 100까지 정수 중에서 20개의 난수를 발생하여 list(혹은 array)를 만드는 코드를 작성하시오. (random seed : 777)

In [82]:
np.random.seed(777)
a = np.random.randint(1,100,20)
print(a)

[48 60 39 88 50 72 30 40 90 47 25 40 19 14 15 33 92 66 83 85]


    (d) 저장된 mymodule에서 정의된 함수를 이용해서 (c)의 list(혹은 array)에서 홀수인 원소들의 평균을 구하는 example code를 작성하시오.

In [80]:
from mymodule import myodd

ModuleNotFoundError: ignored

In [83]:
np.mean(myodd(a))

48 60 39 88 50 72 30 40 90 47 25 40 19 14 15 33 92 66 83 85


43.25

### problem 8

    (a) 다음 인터넷 주소에서 데이터를 불러오는 코드를 작성하시오.

- 데이터 주소 : https://raw.githubusercontent.com/agconti/kaggle-titanic/master/data/train.csv

In [84]:
data = pd.read_csv('https://raw.githubusercontent.com/agconti/kaggle-titanic/master/data/train.csv')

    (b) Survived가 0인 데이터를 추출한 후 처음 4줄만 출력하는 코드를 작성하시오.

In [85]:
data.query('Survived==0')[:4]

PassengerId  Survived  Pclass                      Name   Sex   Age  SibSp  \
0            1         0       3   Braund, Mr. Owen Harris  male  22.0      1   
4            5         0       3  Allen, Mr. William Henry  male  35.0      0   
5            6         0       3          Moran, Mr. James  male   NaN      0   
6            7         0       1   McCarthy, Mr. Timothy J  male  54.0      0   

   Parch     Ticket     Fare Cabin Embarked  
0      0  A/5 21171   7.2500   NaN        S  
4      0     373450   8.0500   NaN        S  
5      0     330877   8.4583   NaN        Q  
6      0      17463  51.8625   E46        S

    (c) Paddengerl가 5 이상이고 Pclass가 3인 데이터를 추출한 후 마지막 4줄만 출력하는 코드를 작성하시오.

In [86]:
data[(data['PassengerId']>=5)&(data['Pclass']==3)].tail(4)

PassengerId  Survived  Pclass                                      Name  \
884          885         0       3                    Sutehall, Mr. Henry Jr   
885          886         0       3      Rice, Mrs. William (Margaret Norton)   
888          889         0       3  Johnston, Miss. Catherine Helen "Carrie"   
890          891         0       3                       Dooley, Mr. Patrick   

        Sex   Age  SibSp  Parch           Ticket    Fare Cabin Embarked  
884    male  25.0      0      0  SOTON/OQ 392076   7.050   NaN        S  
885  female  39.0      0      5           382652  29.125   NaN        Q  
888  female   NaN      1      2       W./C. 6607  23.450   NaN        S  
890    male  32.0      0      0           370376   7.750   NaN        Q