<a href="https://colab.research.google.com/github/hseyeon1006/ESAA_YB/blob/main/ESAA_0317_%EB%AC%B8%EC%A0%9C.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np

#### 26. How to find common values between two arrays? (★☆☆)
```python
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
```
Hint : use `numpy.random.randint(start, end, size)`

In [4]:
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
print(np.intersect1d(Z1,Z2))

[0 2 7 9]


In [5]:
np.random.randint(0,10,10)

array([0, 7, 3, 6, 1, 7, 4, 2, 0, 2])

#### 27. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [6]:
np.sqrt(-1) == np.emath.sqrt(-1)

<ipython-input-6-16339fbc685e>:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1) == np.emath.sqrt(-1)


False

No

#### 28. How to get all the dates corresponding to the month of July 2016? (★★☆)
Hint : modify the code below
```python
Z = np.arange('start', 'end', dtype='datetime64[D]')
```

In [8]:
Z = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(Z)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 29. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)
Hint : use `numpy.add`, `numpy.divide`,`numpy.negative`, `numpy.multiply` and parameter `out` of the funtions

In [9]:
A = np.ones(3)*1
B = np.ones(3)*2
C = np.ones(3)*3
np.add(A,B, out=B)
np.negative(A, out=A)
np.divide(A,2,out=A)
np.multiply(A,B,out=A)

array([-1.5, -1.5, -1.5])

#### 30. Extract the integer part of a random array of positive numbers using 2 different methods (★★☆)
Hint : `%`, `//`

In [10]:
a = np.random.uniform(0,10,10)
print(a)

[6.58419017 2.47030766 5.1575782  3.10149004 6.63587934 5.82274057
 8.22118405 2.60481905 1.37917502 9.40571446]


In [11]:
print(a - a%1)
print(np.floor(a))
print(np.ceil(a)-1)
print(a.astype(int))
print(np.trunc(a))

[6. 2. 5. 3. 6. 5. 8. 2. 1. 9.]
[6. 2. 5. 3. 6. 5. 8. 2. 1. 9.]
[6. 2. 5. 3. 6. 5. 8. 2. 1. 9.]
[6 2 5 3 6 5 8 2 1 9]
[6. 2. 5. 3. 6. 5. 8. 2. 1. 9.]


#### 31. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [12]:
a = np.zeros((5,5))
a+=np.arange(5)
print(a)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 32. Create a random vector of size 10 and sort it (★★☆)

In [13]:
np.linspace(0,1,11,endpoint=False)[1:]

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

#### 33. Consider two random array A and B, check if they are equal (★★☆)
```python
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
```
Hint : Use `numpy.array_equal()`

In [14]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)

equal = np.array_equal(A,B)
print(equal)

False


#### 34. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)
Hint 1 : Note that cartesian coodinate **(x, y)** can be represented as  polar coordinates **(distance from origin to (x,y), angle from the x-axis)**

Hint 2 : Use `numpy.sqrt` and `numpy.arctan2`

In [15]:
a = np.random.random((10,2))
print(a)

X, Y = a[:,0], a[:,1]
R = np.sqrt(X**2+Y**2)
T = np.arctan2(Y,X)
print(R)
print(T)

[[0.86107973 0.50924638]
 [0.66309705 0.36001527]
 [0.3556934  0.17189766]
 [0.75073503 0.82379769]
 [0.88859524 0.29482078]
 [0.10007213 0.72640892]
 [0.67695785 0.88417012]
 [0.84734797 0.51401203]
 [0.89472789 0.28794082]
 [0.83842492 0.76469674]]
[1.00039501 0.75452547 0.39505266 1.11456077 0.93622689 0.73326963
 1.11356577 0.99106355 0.9399191  1.13477639]
[0.53407527 0.49739897 0.45017816 0.83176766 0.32035459 1.43389525
 0.91735922 0.54526759 0.3113525  0.73944017]


#### 35. Create random vector Z of size 10 and replace the maximum value by 0 (★★☆)
Hint : We can see the index of maximum value using `Z.argmax()`

In [16]:
a = np.random.random(10)
print(a)

print(a.argmax())

a[a.argmax()] = 0
print(a)

[0.88637772 0.61107149 0.11647496 0.1298976  0.68033585 0.19340201
 0.55101567 0.49647784 0.70610667 0.08012656]
0
[0.         0.61107149 0.11647496 0.1298976  0.68033585 0.19340201
 0.55101567 0.49647784 0.70610667 0.08012656]


#### 36. How to find the closest value (to a given scalar v) in a vector Z? (★★☆)
```python
Z = np.arange(100)
v = np.random.uniform(0,100)
```
Hint : Coumpute the distances between the each elements of Z and the scalar v. After that, we can see the index of minimum value using `argmin()`.  

In [17]:
Z = np.arange(100)
print(Z)
v = np.random.uniform(0,100)
print(v)

index = (np.abs(Z-v)).argmin()
print(index)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
15.278164227641433
15


#### 37. What is the equivalent of enumerate for numpy arrays? (★★☆)
Hint : Use `numpy.ndenumerate()`or `numpy.ndindex()`

Example of the output :
```python
Z = np.arange(9).reshape(3,3)
```
```python
# output
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
```

In [18]:
Z = np.arange(9).reshape(3,3)
print(Z)

for index, value in np.ndenumerate(Z):
  print(index, value)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


In [20]:
for index in np.ndindex(Z.shape):
  print(index, Z[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 38. How to randomly place p elements in a 2D array? (★★☆)
Hint : modify the code below
```python
n = 'size of a 2D array'
p = 'the number of elements that you want to place'
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace = False),'value that you want to place')
print(Z)
```

In [21]:
n = 10
p = 3
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace = False), 1)
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]]


In [22]:
np.random.choice(range(n*n),p)

array([ 6, 63, 74])

#### 39. How to sort an array below by the nth column? (★★☆)
```python
Z = np.random.randint(0,10,(3,3))
```

In [23]:
Z = np.random.randint(0,10,(3,3))
print(Z)

[[6 2 1]
 [8 5 8]
 [1 3 4]]


In [24]:
# column 1
print(Z[Z[:,0].argsort()])

[[1 3 4]
 [6 2 1]
 [8 5 8]]


In [25]:
# column 2
print(Z[Z[:,1].argsort()])

[[6 2 1]
 [1 3 4]
 [8 5 8]]


In [26]:
# column 3
print(Z[Z[:,2].argsort()])

[[6 2 1]
 [1 3 4]
 [8 5 8]]
