<a href="https://colab.research.google.com/github/hseyeon1006/ESAA_YB/blob/main/ESAA_0313.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

#### 1. Import the numpy package under the name `np` (★☆☆)

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [2]:
print(np.__version__)
np.show_config()

1.22.4
openblas64__info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['/usr/local/lib']
blas_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['/usr/local/lib']
openblas64__lapack_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None), ('HAVE_LAPACKE', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS

#### 3. Create a null vector of size 10 (★☆☆)

In [3]:
a = np.zeros(10)
print(a)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4. How to find the memory size of any array (★☆☆)

In [8]:
a = np.zeros((5,5))
print(a.size, a.itemsize)
print("%d bytes" % (a.size*a.itemsize))

25 8
200 bytes


#### 5. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [7]:
a = np.zeros(10)
a[4] = 1
print(a)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 6. Create a vector with values ranging from 10 to 49 (★☆☆)

In [10]:
a = np.arange(10,50)
print(a)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 7. Reverse a vector (first element becomes last) (★☆☆)

In [11]:
a = np.arange(10,50)
a = a[::-1]
print(a)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 8. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [13]:
a = np.arange(9).reshape(3,3)
print(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 9. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [14]:
a = np.nonzero([1,2,0,0,4,0])
print(a)

(array([0, 1, 4]),)


#### 10. Create a 3x3 identity matrix (★☆☆)
Hint : identity & eye, try to use 'help' to learn how to use two functions of numpy

In [15]:
a = np.eye(3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 11. Create a 3x3x3 array with random values (★☆☆)
Hint : numpy.random.random

In [16]:
a = np.random.random((3,3,3))
print(a)

[[[0.02468348 0.24222214 0.40597183]
  [0.77667673 0.88653476 0.27693374]
  [0.15128857 0.71261736 0.11834367]]

 [[0.57498369 0.67751701 0.80485981]
  [0.90583655 0.97925419 0.88014406]
  [0.64153656 0.04206559 0.53451722]]

 [[0.05554157 0.01133061 0.07332791]
  [0.39196437 0.41958165 0.6824958 ]
  [0.79103951 0.04657178 0.38533651]]]


#### 12. Create a 10x10 array with random values and find the **min**imum and **max**imum values (★☆☆)

In [17]:
a = np.random.random((10,10))
amin, amax = a.min(), a.max()
print(amin, amax)

0.007942627651418843 0.9992940852390102


#### 13. Create a random vector of size 30 and find the **mean** value (★☆☆)

In [19]:
a = np.random.random(30)
m = a.mean()
print(m)

0.6308535431259072


#### 14. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [20]:
a = np.ones((10,10))
a[1:-1, 1:-1] = 0
print(a)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


#### 15. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [ ]:
0 * np.nan
#nan
np.nan == np.nan
#False
np.inf > np.nan
#False
np.nan - np.nan
#nan
np.nan in set([np.nan])
#True
0.3 == 3 * 0.1
#False

#### 16. Create a 5x5 matrix with values 1,2,3,4 just below the **diag**onal (★☆☆)

In [64]:
a = np.diag(1+np.arange(4), k=-1) #k=-1 왼쪽으로 한 칸씩 민 것
print(a)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 17. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [62]:
a = np.zeros((8,8), dtype=int)
a[1::2,::2] = 1 #1에서 끝까지 간격이 2인걸 1로 채우기
a[::2,1::2] = 1
print(a)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 18. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)
Hint : use 'numpy.unravel_index(value, (x, y, z))

In [36]:
print(np.unravel_index(99,(6,7,8)))

(1, 5, 3)


#### 19. Normalize a 5x5 random matrix (★☆☆)
Hint : $Z = \frac{X - \overline{X}}{S}$

In [37]:
a = np.random.random((5,5))
z = (a - np.mean(a))/(np.std(a))
print(z)

[[-0.05208769  0.15019476  1.29084677  0.25265902 -1.31218393]
 [-1.24835788 -0.87139667  1.5847233  -1.0785979   1.11692552]
 [-0.47392249  0.01244689 -1.57040138 -0.38681831  0.08996307]
 [ 0.97394101 -0.84034603  0.95624954  0.91320179 -0.60873023]
 [ 1.27599467  1.23505722 -1.57561807 -0.91951777  1.08577479]]


#### 20. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)
Hint : modify the code below
```python
numpy.dtype([(value, numpy.ubyte), … , (value, numpy.ubyte)])
```

In [59]:
color = np.dtype([("r", np.ubyte),
                  ("g", np.ubyte),
                  ("b", np.ubyte),
                  ("a", np.ubyte)])

In [60]:
print(color)

[('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')]


#### 21. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [49]:
a = np.dot(np.ones((5,3)), np.ones((3,2)))
print(a)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


#### 22. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [50]:
a = np.arange(11)
a[(3<=a) & (a<=8)]*=-1
print(a)

[ 0  1  2 -3 -4 -5 -6 -7 -8  9 10]


#### 23. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [51]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


#### 24. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [ ]:
Z = np.arange(11)

print(Z**Z)
# 오류

print(2 << Z >> 2)
#[  0   1   2   4   8  16  32  64 128 256 512]

print(Z <- Z)
#[False False False False False False False False False False False]

print(1j*Z)
#[0. +0.j 0. +1.j 0. +2.j 0. +3.j 0. +4.j 0. +5.j 0. +6.j 0. +7.j 0. +8.j  0. +9.j 0.+10.j]

print(Z/1/1)
#[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]

print(Z<Z>Z)
#오류

#### 25. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [ ]:
print(np.array(0) / np.array(0))
#nan

print(np.array(0) // np.array(0))
#0

print(np.array([np.nan]).astype(int).astype(float))
#[-9.22337204e+18]